name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t image_name .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ https://github.com/Grilindor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker Image to Registry
        run: docker push ghcr.io/${{ https://github.com/Grilindor }}/image_name
